--------------------------------------------------------
--  파일이 생성됨 - 일요일-3월-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."ATTACH" 
   (	"ANO" NUMBER, 
	"BNO" NUMBER, 
	"ORIGINFILENAME" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"PATH" VARCHAR2(1000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(500 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"CONTENT" CLOB, 
	"REF" NUMBER, 
	"REF_STEP" NUMBER, 
	"REF_LEVEL" NUMBER, 
	"REGDATE" DATE, 
	"HIT" NUMBER, 
	"BRD_GB" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BRD_GB
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."BRD_GB" 
   (	"BRD_GB" VARCHAR2(20 BYTE), 
	"BRD_GB_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAT
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."CHAT" 
   (	"CNO" NUMBER, 
	"FROMID" VARCHAR2(20 BYTE), 
	"TOID" VARCHAR2(20 BYTE), 
	"CONTENT" CLOB, 
	"REGDATE" DATE, 
	"READ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DDITMEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."DDITMEMBER" 
   (	"DNO" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDR1" VARCHAR2(500 BYTE), 
	"ADDR2" VARCHAR2(500 BYTE), 
	"KIND" VARCHAR2(100 BYTE), 
	"TEL" VARCHAR2(50 BYTE), 
	"ROOM" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVALUATION
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."EVALUATION" 
   (	"ENO" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"REF" NUMBER, 
	"REF_STEP" NUMBER, 
	"REF_LEVEL" NUMBER, 
	"LECTURENAME" VARCHAR2(50 BYTE), 
	"PROFESSORNAME" VARCHAR2(50 BYTE), 
	"YEAR" NUMBER, 
	"MONTH" VARCHAR2(20 BYTE), 
	"DIVIDE" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(50 BYTE), 
	"CONTENT" CLOB, 
	"TOTALSCORE" VARCHAR2(10 BYTE), 
	"LIKECOUNT" NUMBER, 
	"BRD_GB" VARCHAR2(20 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GR
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GR" 
   (	"GNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"GOAL" VARCHAR2(200 BYTE), 
	"CODE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRATTACH
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRATTACH" 
   (	"GANO" NUMBER, 
	"GBNO" NUMBER, 
	"GNO" NUMBER, 
	"ORIGINFILENAME" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"PATH" VARCHAR2(1000 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRBOARD
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRBOARD" 
   (	"GBNO" NUMBER, 
	"GNO" NUMBER, 
	"TITLE" VARCHAR2(500 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"CONTENT" CLOB, 
	"REGDATE" DATE, 
	"HIT" NUMBER, 
	"GOOD" NUMBER, 
	"BAD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table GRCHAT
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRCHAT" 
   (	"GCNO" NUMBER, 
	"GNO" NUMBER, 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRDDAY
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRDDAY" 
   (	"DNO" NUMBER, 
	"GNO" NUMBER, 
	"CONTENT" VARCHAR2(200 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"GRDATE" DATE, 
	"YEAR" VARCHAR2(20 BYTE), 
	"MONTH" VARCHAR2(20 BYTE), 
	"DAY" VARCHAR2(20 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRFILE
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRFILE" 
   (	"FNO" NUMBER, 
	"FILENAME" VARCHAR2(200 BYTE), 
	"ORIGINFILENAME" VARCHAR2(200 BYTE), 
	"FILETYPE" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(500 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"GNO" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRLIKECHECK
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRLIKECHECK" 
   (	"GLNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"GBNO" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRMEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRMEMBER" 
   (	"GMNO" NUMBER, 
	"GNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRMEMO
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRMEMO" 
   (	"MNO" NUMBER, 
	"GNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUTLIST
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GROUTLIST" 
   (	"GONO" NUMBER, 
	"GNO" NUMBER, 
	"ID" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRSCHEDULE
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRSCHEDULE" 
   (	"SNO" NUMBER, 
	"GNO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"STARTDATE" VARCHAR2(50 BYTE), 
	"ENDDATE" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRTODOLIST
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."GRTODOLIST" 
   (	"GTNO" NUMBER, 
	"GNO" NUMBER, 
	"GMNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"VERTIFY" VARCHAR2(100 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LECTUREREPLY
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."LECTUREREPLY" 
   (	"RNO" NUMBER, 
	"ENO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"CONTENT" CLOB, 
	"REF" NUMBER, 
	"REF_STEP" NUMBER, 
	"REF_LEVEL" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LIKECHECK
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."LIKECHECK" 
   (	"LNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"ENO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"REGDATE" DATE, 
	"AUTHORITY" VARCHAR2(20 BYTE), 
	"FILENAME" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMO
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."MEMO" 
   (	"MNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."REPLY" 
   (	"RNO" NUMBER, 
	"BNO" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"CONTENT" CLOB, 
	"REF" NUMBER, 
	"REF_STEP" NUMBER, 
	"REF_LEVEL" NUMBER, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."REPORT" 
   (	"RPNO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" CLOB, 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "PROJECT3"."SCHEDULE" 
   (	"SNO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"STARTDATE" VARCHAR2(50 BYTE), 
	"ENDDATE" VARCHAR2(50 BYTE), 
	"ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT3.ATTACH
SET DEFINE OFF;
REM INSERTING into PROJECT3.BOARD
SET DEFINE OFF;
REM INSERTING into PROJECT3.BRD_GB
SET DEFINE OFF;
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('A01','공지사항');
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('B01','수강후기');
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('C01','자유게시판');
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('D01','자료실');
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('E01','QNA');
Insert into PROJECT3.BRD_GB (BRD_GB,BRD_GB_NAME) values ('F01','FAQ');
REM INSERTING into PROJECT3.CHAT
SET DEFINE OFF;
REM INSERTING into PROJECT3.DDITMEMBER
SET DEFINE OFF;
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (1,'차경석','대전 광역시 대덕구 오정동','하우스','풀스택','1037955271',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (2,'강지원','대전 광역시 대덕구 오정동','하우스','풀스택','1056239656',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (3,'김동민','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (4,'김동희','대전 광역시 대덕구 오정동','하우스','풀스택','1096584521',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (5,'김민지','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (6,'김용진','대전 광역시 대덕구 오정동','하우스','풀스택','1023654785',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (7,'김인혁','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (8,'김진용','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (9,'박범영','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (10,'박병규','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (11,'배현태','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (12,'심민규','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (13,'여인욱','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (14,'이나정','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (15,'이승민','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (16,'이영섭','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (17,'이윤혜','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (18,'이지향','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (19,'임정혁','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (20,'임형묵','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (21,'장성보','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (22,'정선영','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (23,'정회립','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (24,'최준영','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
Insert into PROJECT3.DDITMEMBER (DNO,NAME,ADDR1,ADDR2,KIND,TEL,ROOM,REGDATE) values (25,'허지영','대전 광역시 대덕구 오정동','하우스','풀스택','1078451236',403,to_date('21/02/06','RR/MM/DD'));
REM INSERTING into PROJECT3.EVALUATION
SET DEFINE OFF;
REM INSERTING into PROJECT3.GR
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRATTACH
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRBOARD
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRCHAT
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRDDAY
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRFILE
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRLIKECHECK
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRMEMBER
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRMEMO
SET DEFINE OFF;
REM INSERTING into PROJECT3.GROUTLIST
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRSCHEDULE
SET DEFINE OFF;
REM INSERTING into PROJECT3.GRTODOLIST
SET DEFINE OFF;
REM INSERTING into PROJECT3.LECTUREREPLY
SET DEFINE OFF;
REM INSERTING into PROJECT3.LIKECHECK
SET DEFINE OFF;
REM INSERTING into PROJECT3.MEMBER
SET DEFINE OFF;
Insert into PROJECT3.MEMBER (ID,PWD,NAME,EMAIL,TEL,REGDATE,AUTHORITY,FILENAME) values ('mimi','Rufwjs953!','차경석','ckrudtjr938@gmail.com','01079975271',to_date('21/02/06','RR/MM/DD'),'user','b0b202a7-c274-4955-89a1-b0cbaf59b52e_552a6838c5a3bd568d7ac049e6be9c94.jpg');
REM INSERTING into PROJECT3.MEMO
SET DEFINE OFF;
REM INSERTING into PROJECT3.REPLY
SET DEFINE OFF;
REM INSERTING into PROJECT3.REPORT
SET DEFINE OFF;
REM INSERTING into PROJECT3.SCHEDULE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007100
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007100" ON "PROJECT3"."ATTACH" ("ANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007015
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007015" ON "PROJECT3"."BOARD" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007005
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007005" ON "PROJECT3"."BRD_GB" ("BRD_GB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007057
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007057" ON "PROJECT3"."CHAT" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007166
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007166" ON "PROJECT3"."DDITMEMBER" ("DNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007041
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007041" ON "PROJECT3"."EVALUATION" ("ENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007068
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007068" ON "PROJECT3"."GR" ("GNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007142
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007142" ON "PROJECT3"."GRATTACH" ("GANO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007136
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007136" ON "PROJECT3"."GRBOARD" ("GBNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007088
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007088" ON "PROJECT3"."GRCHAT" ("GCNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007126
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007126" ON "PROJECT3"."GRDDAY" ("DNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007082
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007082" ON "PROJECT3"."GRFILE" ("FNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007148
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007148" ON "PROJECT3"."GRLIKECHECK" ("GLNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007072
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007072" ON "PROJECT3"."GRMEMBER" ("GMNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007116
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007116" ON "PROJECT3"."GRMEMO" ("MNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007175
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007175" ON "PROJECT3"."GROUTLIST" ("GONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007095
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007095" ON "PROJECT3"."GRSCHEDULE" ("SNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007109
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007109" ON "PROJECT3"."GRTODOLIST" ("GTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007157
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007157" ON "PROJECT3"."LECTUREREPLY" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007045
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007045" ON "PROJECT3"."LIKECHECK" ("LNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007004
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007004" ON "PROJECT3"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007170
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007170" ON "PROJECT3"."MEMO" ("MNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007024
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007024" ON "PROJECT3"."REPLY" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007050
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007050" ON "PROJECT3"."REPORT" ("RPNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007062
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT3"."SYS_C007062" ON "PROJECT3"."SCHEDULE" ("SNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."ATTACH" ADD PRIMARY KEY ("ANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."ATTACH" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."ATTACH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."ATTACH" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."BOARD" ADD PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("BRD_GB" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("REF_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("REF_STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRD_GB
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."BRD_GB" ADD PRIMARY KEY ("BRD_GB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHAT
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."CHAT" ADD PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."CHAT" MODIFY ("READ" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."CHAT" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."CHAT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."CHAT" MODIFY ("TOID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."CHAT" MODIFY ("FROMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DDITMEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."DDITMEMBER" ADD PRIMARY KEY ("DNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("ROOM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("KIND" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("ADDR2" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("ADDR1" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."DDITMEMBER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."EVALUATION" ADD PRIMARY KEY ("ENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("BRD_GB" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("LIKECOUNT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("TOTALSCORE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("DIVIDE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("PROFESSORNAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("LECTURENAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("REF_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("REF_STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."EVALUATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GR
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GR" ADD PRIMARY KEY ("GNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GR" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GR" MODIFY ("GOAL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GR" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRATTACH
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRATTACH" ADD PRIMARY KEY ("GANO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRATTACH" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRATTACH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRATTACH" MODIFY ("GNO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRATTACH" MODIFY ("GBNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRBOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRBOARD" ADD PRIMARY KEY ("GBNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("BAD" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("GOOD" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("HIT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRBOARD" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRCHAT
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRCHAT" ADD PRIMARY KEY ("GCNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRCHAT" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRCHAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRCHAT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRCHAT" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRDDAY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRDDAY" ADD PRIMARY KEY ("DNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("DAY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("MONTH" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("GRDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRDDAY" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRFILE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRFILE" ADD PRIMARY KEY ("FNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("GNO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("UPLOADPATH" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("FILETYPE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("ORIGINFILENAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRFILE" MODIFY ("FILENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRLIKECHECK
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRLIKECHECK" ADD PRIMARY KEY ("GLNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRLIKECHECK" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRLIKECHECK" MODIFY ("GBNO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRLIKECHECK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRMEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRMEMBER" ADD PRIMARY KEY ("GMNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRMEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRMEMBER" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRMEMO
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRMEMO" ADD PRIMARY KEY ("MNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRMEMO" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRMEMO" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRMEMO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRMEMO" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GROUTLIST
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GROUTLIST" ADD PRIMARY KEY ("GONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GROUTLIST" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GROUTLIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GROUTLIST" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRSCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRSCHEDULE" ADD PRIMARY KEY ("SNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRSCHEDULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRSCHEDULE" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRSCHEDULE" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRSCHEDULE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRSCHEDULE" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRTODOLIST
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRTODOLIST" ADD PRIMARY KEY ("GTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("VERTIFY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("GMNO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."GRTODOLIST" MODIFY ("GNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LECTUREREPLY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."LECTUREREPLY" ADD PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("REF_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("REF_STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LECTUREREPLY" MODIFY ("ENO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIKECHECK
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."LIKECHECK" ADD PRIMARY KEY ("LNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."LIKECHECK" MODIFY ("ENO" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."LIKECHECK" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMBER" MODIFY ("PWD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMO
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."MEMO" ADD PRIMARY KEY ("MNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."MEMO" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMO" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."MEMO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."REPLY" ADD PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("REGDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("REF_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("REF_STEP" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("REF" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPLY" MODIFY ("BNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."REPORT" ADD PRIMARY KEY ("RPNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."REPORT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPORT" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."REPORT" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."SCHEDULE" ADD PRIMARY KEY ("SNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT3"."SCHEDULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."SCHEDULE" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."SCHEDULE" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT3"."SCHEDULE" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."ATTACH" ADD CONSTRAINT "ATTACH_BOARD" FOREIGN KEY ("BNO")
	  REFERENCES "PROJECT3"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."BOARD" ADD CONSTRAINT "BRD_GB_BOARD" FOREIGN KEY ("BRD_GB")
	  REFERENCES "PROJECT3"."BRD_GB" ("BRD_GB") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVALUATION
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."EVALUATION" ADD CONSTRAINT "BRD_GB_EVALUATION" FOREIGN KEY ("BRD_GB")
	  REFERENCES "PROJECT3"."BRD_GB" ("BRD_GB") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GR
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GR" ADD CONSTRAINT "STUDYGROUP_MEMBER" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT3"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRATTACH
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRATTACH" ADD CONSTRAINT "GRATTACH_BOARD" FOREIGN KEY ("GBNO")
	  REFERENCES "PROJECT3"."GRBOARD" ("GBNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROJECT3"."GRATTACH" ADD CONSTRAINT "GRATTACH_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRBOARD
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRBOARD" ADD CONSTRAINT "GNO_GRBOARD" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRCHAT
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRCHAT" ADD CONSTRAINT "GRCHAT_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRDDAY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRDDAY" ADD CONSTRAINT "GRDDAY_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRFILE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRFILE" ADD CONSTRAINT "GRFILE_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRLIKECHECK
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRLIKECHECK" ADD CONSTRAINT "GRLIKECHECK_GRBOARD" FOREIGN KEY ("GBNO")
	  REFERENCES "PROJECT3"."GRBOARD" ("GBNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRMEMBER
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRMEMBER" ADD CONSTRAINT "STGROUPMEMBER_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROJECT3"."GRMEMBER" ADD CONSTRAINT "STGROUPMEMBER_MEMBER" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT3"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRMEMO
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRMEMO" ADD CONSTRAINT "GRMEMO_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUTLIST
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GROUTLIST" ADD CONSTRAINT "OUT_GROUP" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRSCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRSCHEDULE" ADD CONSTRAINT "GR_SCHEDULE" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRTODOLIST
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."GRTODOLIST" ADD CONSTRAINT "GRTODOLIST_GNO" FOREIGN KEY ("GNO")
	  REFERENCES "PROJECT3"."GR" ("GNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROJECT3"."GRTODOLIST" ADD CONSTRAINT "GRTODOLIST_ID" FOREIGN KEY ("GMNO")
	  REFERENCES "PROJECT3"."GRMEMBER" ("GMNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LECTUREREPLY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."LECTUREREPLY" ADD CONSTRAINT "LECTURE_REPLY_BOARD" FOREIGN KEY ("ENO")
	  REFERENCES "PROJECT3"."EVALUATION" ("ENO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LIKECHECK
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."LIKECHECK" ADD CONSTRAINT "LIKECHECK_EVALUATION" FOREIGN KEY ("ENO")
	  REFERENCES "PROJECT3"."EVALUATION" ("ENO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMO
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."MEMO" ADD CONSTRAINT "MEMBER_MEMO" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT3"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."REPLY" ADD CONSTRAINT "REPLY_BOARD" FOREIGN KEY ("BNO")
	  REFERENCES "PROJECT3"."BOARD" ("BNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."REPORT" ADD CONSTRAINT "REPORT_MEMBER" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT3"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "PROJECT3"."SCHEDULE" ADD CONSTRAINT "SCHEDULE_MEMBER" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT3"."MEMBER" ("ID") ON DELETE CASCADE ENABLE;
